services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/code/src
    env_file:
      - .env
    depends_on:
      - redis

  celery-worker:
    build: ./backend
    command: celery -A celery_worker.celery_app worker --loglevel=info
    volumes:
      - ./backend/src:/code/src
    env_file:
      - .env
    depends_on:
      - backend
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # --- ADD THIS ARGS SECTION ---
      # This is a cache-busting mechanism.
      args:
        CACHE_DATE: ${CACHE_DATE:-1}
    ports:
      - "3000:80"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  backend-models: